import os
from collections.abc import Iterator
from contextlib import contextmanager
from typing import TypedDict

import psycopg
from dotenv import load_dotenv
from psycopg.rows import dict_row


load_dotenv()

DATABASE_QUERY_TIMEOUT_MILLISECONDS = 5_000
CANCELLABLE_ORDER_STATUSES = frozenset({"pending", "paid", "processing", "shipped"})
CANCELLATION_REJECTION_REASONS = {
    "cancelled": "already_cancelled",
    "delivered": "delivered_order",
    "refunded": "refunded_order",
}


class CancellationResult(TypedDict):
    found: bool
    order_id: str
    cancelled: bool
    status: str | None
    previous_status: str | None
    reason: str


def connection_parameters() -> dict[str, str | int]:
    return {
        "host": os.environ["POSTGRES_HOST"],
        "port": os.environ["POSTGRES_PORT"],
        "dbname": os.environ["POSTGRES_DB"],
        "user": os.environ["POSTGRES_USER"],
        "password": os.environ["POSTGRES_PASSWORD"],
        "connect_timeout": 5,
        "options": f"-c statement_timeout={DATABASE_QUERY_TIMEOUT_MILLISECONDS}",
    }


@contextmanager
def database_connection() -> Iterator[psycopg.Connection]:
    with psycopg.connect(**connection_parameters(), row_factory=dict_row) as connection:
        yield connection


def initialize_database() -> None:
    with database_connection() as connection:
        connection.execute(
            """
            CREATE TABLE IF NOT EXISTS products (
                sku TEXT PRIMARY KEY,
                name TEXT NOT NULL,
                category TEXT NOT NULL CHECK (category IN ('laptop', 'printer', 'spare_part')),
                price NUMERIC(10, 2) NOT NULL CHECK (price > 0)
            )
            """
        )
        connection.execute(
            """
            CREATE TABLE IF NOT EXISTS orders (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                customer_id TEXT NOT NULL,
                product_sku TEXT NOT NULL REFERENCES products(sku),
                quantity INTEGER NOT NULL CHECK (quantity BETWEEN 1 AND 10),
                status TEXT NOT NULL CHECK (
                    status IN ('pending', 'paid', 'processing', 'shipped',
                               'delivered', 'cancelled', 'refunded')
                ),
                created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
            )
            """
        )
        connection.execute(
            """
            CREATE TABLE IF NOT EXISTS user_memories (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                user_id TEXT NOT NULL,
                memory_key TEXT NOT NULL,
                memory_value TEXT NOT NULL,
                created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                updated_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                UNIQUE (user_id, memory_key)
            )
            """
        )
        # Conversations live in Redis for three days (see agent_graph.py). What
        # outlives them is a short summary plus its embedding, so past
        # conversations stay searchable without retaining full transcripts.
        connection.execute("CREATE EXTENSION IF NOT EXISTS vector")
        connection.execute(
            """
            CREATE TABLE IF NOT EXISTS conversation_summaries (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                customer_id TEXT NOT NULL,
                thread_id TEXT NOT NULL,
                summary TEXT NOT NULL,
                embedding vector(1024) NOT NULL,
                message_count INTEGER NOT NULL DEFAULT 0,
                created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                UNIQUE (customer_id, thread_id)
            )
            """
        )
        connection.execute(
            """
            CREATE INDEX IF NOT EXISTS conversation_summaries_embedding_idx
            ON conversation_summaries USING hnsw (embedding vector_cosine_ops)
            """
        )
        connection.execute(
            """
            CREATE TABLE IF NOT EXISTS refunds (
                id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                order_id BIGINT NOT NULL UNIQUE REFERENCES orders(id),
                amount NUMERIC(10, 2) NOT NULL CHECK (amount > 0),
                reason TEXT NOT NULL,
                idempotency_key TEXT NOT NULL UNIQUE,
                created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
            )
            """
        )

        products = [
            ("LAP-001", "Everyday Laptop 14", "laptop", "749.00"),
            ("LAP-002", "Developer Laptop 16", "laptop", "1299.00"),
            ("PRN-001", "Office Laser Printer", "printer", "329.00"),
            ("PRN-002", "Home Inkjet Printer", "printer", "149.00"),
            ("SP-001", "Laptop Charger 65W", "spare_part", "49.00"),
            ("SP-002", "Printer Toner", "spare_part", "79.00"),
        ]
        with connection.cursor() as cursor:
            cursor.executemany(
                """
                INSERT INTO products (sku, name, category, price)
                VALUES (%s, %s, %s, %s)
                ON CONFLICT (sku) DO NOTHING
                """,
                products,
            )

        statuses = [
            "pending", "paid", "processing", "shipped",
            "delivered", "cancelled", "refunded",
        ]
        product_skus = [product[0] for product in products]
        seed_orders = [
            (
                number,
                f"CUS-{((number - 1) % 30) + 1:03d}",
                product_skus[(number - 1) % len(product_skus)],
                ((number - 1) % 3) + 1,
                statuses[(number - 1) % len(statuses)],
                f"2026-01-{((number - 1) % 28) + 1:02d}T00:00:00+00:00",
            )
            for number in range(1, 121)
        ]
        with connection.cursor() as cursor:
            cursor.executemany(
                """
                INSERT INTO orders (id, customer_id, product_sku, quantity, status, created_at)
                VALUES (%s, %s, %s, %s, %s, %s)
                ON CONFLICT (id) DO NOTHING
                """,
                seed_orders,
            )
        connection.execute(
            """
            SELECT setval(
                pg_get_serial_sequence('orders', 'id'),
                (SELECT MAX(id) FROM orders)
            )
            """
        )


ORDER_SELECT = """
    SELECT o.id, o.customer_id, o.quantity, o.status, o.created_at,
           p.sku, p.name, p.category, p.price,
           p.price * o.quantity AS total
    FROM orders o
    JOIN products p ON p.sku = o.product_sku
"""


def list_product_rows(category: str | None = None) -> list[dict]:
    query = "SELECT sku, name, category, price FROM products"
    parameters: tuple[str, ...] = ()
    if category is not None:
        query += " WHERE category = %s"
        parameters = (category,)
    query += " ORDER BY sku"
    with database_connection() as connection:
        return connection.execute(query, parameters).fetchall()


def database_counts() -> tuple[int, int]:
    with database_connection() as connection:
        order_count = connection.execute("SELECT COUNT(*) AS count FROM orders").fetchone()
        product_count = connection.execute("SELECT COUNT(*) AS count FROM products").fetchone()
        return order_count["count"], product_count["count"]


def list_order_rows(
    status: str | None,
    limit: int,
    customer_id: str | None = None,
) -> list[dict]:
    """List orders, optionally narrowed to one customer.

    customer_id is applied in SQL rather than filtered afterwards, so a caller
    scoped to one customer can never receive another customer's row.
    """
    query = ORDER_SELECT
    parameters: list[object] = []
    clauses: list[str] = []
    if status is not None:
        clauses.append("o.status = %s")
        parameters.append(status)
    if customer_id is not None:
        clauses.append("o.customer_id = %s")
        parameters.append(customer_id)
    if clauses:
        query += " WHERE " + " AND ".join(clauses)
    query += " ORDER BY o.id LIMIT %s"
    parameters.append(limit)
    with database_connection() as connection:
        return connection.execute(query, parameters).fetchall()


# Order lookups for a customer always filter on customer_id, so another
# customer's order looks exactly like a missing one.
def get_order_status_row(order_number: int, customer_id: str) -> dict | None:
    with database_connection() as connection:
        return connection.execute(
            "SELECT id, status FROM orders WHERE id = %s AND customer_id = %s",
            (order_number, customer_id),
        ).fetchone()


def cancel_order_row(order_number: int, customer_id: str) -> CancellationResult:
    order_id = f"ORD-{order_number:03d}"
    with database_connection() as connection:
        order = connection.execute(
            "SELECT id, status FROM orders WHERE id = %s AND customer_id = %s FOR UPDATE",
            (order_number, customer_id),
        ).fetchone()
        if order is None:
            return {
                "found": False,
                "order_id": order_id,
                "cancelled": False,
                "status": None,
                "previous_status": None,
                "reason": "order_not_found",
            }

        previous_status = order["status"]
        if previous_status not in CANCELLABLE_ORDER_STATUSES:
            return {
                "found": True,
                "order_id": f"ORD-{order['id']:03d}",
                "cancelled": False,
                "status": previous_status,
                "previous_status": previous_status,
                "reason": CANCELLATION_REJECTION_REASONS.get(
                    previous_status,
                    "status_not_cancellable",
                ),
            }

        connection.execute(
            "UPDATE orders SET status = 'cancelled' WHERE id = %s",
            (order_number,),
        )
        return {
            "found": True,
            "order_id": f"ORD-{order['id']:03d}",
            "cancelled": True,
            "status": "cancelled",
            "previous_status": previous_status,
            "reason": "cancelled",
        }


def get_refund_order_row(order_number: int, customer_id: str) -> dict | None:
    with database_connection() as connection:
        return connection.execute(
            """
            SELECT o.id, o.status, p.price * o.quantity AS total
            FROM orders o
            JOIN products p ON p.sku = o.product_sku
            WHERE o.id = %s AND o.customer_id = %s
            """,
            (order_number, customer_id),
        ).fetchone()


def refund_order_row(
    order_number: int,
    customer_id: str,
    reason: str,
    idempotency_key: str,
) -> dict | None:
    with database_connection() as connection:
        order = connection.execute(
            """
            SELECT o.id, o.status, p.price * o.quantity AS total
            FROM orders o
            JOIN products p ON p.sku = o.product_sku
            WHERE o.id = %s AND o.customer_id = %s
            FOR UPDATE OF o
            """,
            (order_number, customer_id),
        ).fetchone()
        if order is None:
            return None

        existing = connection.execute(
            "SELECT amount FROM refunds WHERE order_id = %s",
            (order_number,),
        ).fetchone()
        if existing is not None:
            return {
                "id": order_number,
                "status": "refunded",
                "amount": existing["amount"],
                "refunded": False,
                "reason": "already_refunded",
            }

        if order["status"] != "delivered":
            return {
                "id": order_number,
                "status": order["status"],
                "amount": order["total"],
                "refunded": False,
                "reason": "order_not_delivered",
            }

        connection.execute(
            """
            INSERT INTO refunds (order_id, amount, reason, idempotency_key)
            VALUES (%s, %s, %s, %s)
            """,
            (order_number, order["total"], reason, idempotency_key),
        )
        connection.execute(
            "UPDATE orders SET status = 'refunded' WHERE id = %s",
            (order_number,),
        )
        return {
            "id": order_number,
            "status": "refunded",
            "amount": order["total"],
            "refunded": True,
        }


def create_order_row(customer_id: str, product_sku: str, quantity: int) -> dict | None:
    with database_connection() as connection:
        product = connection.execute(
            "SELECT 1 FROM products WHERE sku = %s", (product_sku,)
        ).fetchone()
        if product is None:
            return None

        created = connection.execute(
            """
            INSERT INTO orders (customer_id, product_sku, quantity, status)
            VALUES (%s, %s, %s, 'pending')
            RETURNING id
            """,
            (customer_id, product_sku, quantity),
        ).fetchone()
        return connection.execute(
            ORDER_SELECT + " WHERE o.id = %s", (created["id"],)
        ).fetchone()


def save_user_memory(user_id: str, memory_key: str, memory_value: str) -> dict:
    with database_connection() as connection:
        return connection.execute(
            """
            INSERT INTO user_memories (user_id, memory_key, memory_value)
            VALUES (%s, %s, %s)
            ON CONFLICT (user_id, memory_key) DO UPDATE
            SET memory_value = EXCLUDED.memory_value,
                updated_at = CURRENT_TIMESTAMP
            RETURNING user_id, memory_key, memory_value, created_at, updated_at
            """,
            (user_id, memory_key, memory_value),
        ).fetchone()


def get_user_memories(user_id: str) -> list[dict]:
    with database_connection() as connection:
        return connection.execute(
            """
            SELECT memory_key, memory_value
            FROM user_memories
            WHERE user_id = %s
            ORDER BY memory_key
            """,
            (user_id,),
        ).fetchall()


def delete_user_memory(user_id: str, memory_key: str) -> bool:
    with database_connection() as connection:
        result = connection.execute(
            "DELETE FROM user_memories WHERE user_id = %s AND memory_key = %s",
            (user_id, memory_key),
        )
        return result.rowcount > 0


def save_conversation_summary(
    customer_id: str,
    thread_id: str,
    summary: str,
    embedding: list[float],
    message_count: int,
) -> None:
    """Store (or replace) the summary for one conversation."""
    vector_literal = "[" + ",".join(repr(float(v)) for v in embedding) + "]"
    with database_connection() as connection:
        connection.execute(
            """
            INSERT INTO conversation_summaries
                (customer_id, thread_id, summary, embedding, message_count)
            VALUES (%s, %s, %s, %s, %s)
            ON CONFLICT (customer_id, thread_id) DO UPDATE SET
                summary = EXCLUDED.summary,
                embedding = EXCLUDED.embedding,
                message_count = EXCLUDED.message_count,
                created_at = CURRENT_TIMESTAMP
            """,
            (customer_id, thread_id, summary, vector_literal, message_count),
        )


def search_conversation_summaries(
    customer_id: str,
    embedding: list[float],
    limit: int = 5,
) -> list[dict]:
    """Nearest summaries for one customer.

    customer_id is applied in SQL, so a search can never surface another
    customer's conversation however similar it is.
    """
    vector_literal = "[" + ",".join(repr(float(v)) for v in embedding) + "]"
    with database_connection() as connection:
        return connection.execute(
            """
            SELECT thread_id, summary, message_count, created_at,
                   1 - (embedding <=> %s) AS similarity
            FROM conversation_summaries
            WHERE customer_id = %s
            ORDER BY embedding <=> %s
            LIMIT %s
            """,
            (vector_literal, customer_id, vector_literal, limit),
        ).fetchall()
